// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlF_DYhHpnkunpZxa5YYwHJgdBlHjkeTs',
    appId: '1:535535458915:web:616f19f06d6b34e1c03656',
    messagingSenderId: '535535458915',
    projectId: 'note-app-b7d78',
    authDomain: 'note-app-b7d78.firebaseapp.com',
    databaseURL: 'https://note-app-b7d78-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'note-app-b7d78.appspot.com',
    measurementId: 'G-FBFNFT3ELS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnoLw_WdyMyI2kBSc51ZDxHvn7CCzX9G4',
    appId: '1:535535458915:android:b804bccc4230313ec03656',
    messagingSenderId: '535535458915',
    projectId: 'note-app-b7d78',
    databaseURL: 'https://note-app-b7d78-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'note-app-b7d78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJHp3inISjER55pIf-xk2PDut4GLFrARI',
    appId: '1:535535458915:ios:3ea554238bffc1e8c03656',
    messagingSenderId: '535535458915',
    projectId: 'note-app-b7d78',
    databaseURL: 'https://note-app-b7d78-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'note-app-b7d78.appspot.com',
    iosClientId: '535535458915-aqmn1sgctutcei1u3ra70142nva0hdr2.apps.googleusercontent.com',
    iosBundleId: 'com.kambathagothi.noteapp.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJHp3inISjER55pIf-xk2PDut4GLFrARI',
    appId: '1:535535458915:ios:3ea554238bffc1e8c03656',
    messagingSenderId: '535535458915',
    projectId: 'note-app-b7d78',
    databaseURL: 'https://note-app-b7d78-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'note-app-b7d78.appspot.com',
    iosClientId: '535535458915-aqmn1sgctutcei1u3ra70142nva0hdr2.apps.googleusercontent.com',
    iosBundleId: 'com.kambathagothi.noteapp.noteApp',
  );
}
